const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];
const toys=[{w:'teddy bear',th:'ตุ๊กตาหมี',e:'🧸'},{w:'car',th:'รถของเล่น',e:'🚗'},{w:'doll',th:'ตุ๊กตา',e:'🪆'},{w:'robot',th:'หุ่นยนต์',e:'🤖'},{w:'puzzle',th:'เกมต่อภาพ',e:'🧩'},{w:'ball',th:'ลูกบอล',e:'🏐'},{w:'train',th:'รถไฟของเล่น',e:'🚂'},{w:'kite',th:'ว่าว',e:'🪁'}];
const stages=['vocab','listen','read','grammar','speak','create'];let total=0,stageScore=0,current='vocab',done=new Set();
function show(id){screens.forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function speak(t,r=.82){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=r;u.pitch=1.05;speechSynthesis.speak(u)}
function beep(ok=true){const ac=window._ac||(window._ac=new (window.AudioContext||window.webkitAudioContext)());const o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.frequency.value=ok?720:190;o.type=ok?'sine':'sawtooth';g.gain.value=.12;o.start();g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.25);o.stop(ac.currentTime+.25)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function add(n){stageScore+=n;total+=n;$('#stageScore').textContent=stageScore}
function finish(t){done.add(current);$('#resultText').textContent=t;$('#result').showModal()}
function label(s){return({vocab:'Vocabulary',listen:'Listening',read:'Reading',grammar:'Grammar',speak:'Speaking',create:'Create & Draw'})[s]}
function menu(){show('#menu');$('#studentLabel').textContent=$('#studentName').value.trim()||'Player';$('#totalScore').textContent=total;$('#badges').innerHTML=stages.map((s,i)=>`<span class="${done.has(s)?'done':''}">${i+1}. ${label(s)}</span>`).join('')}
$('#startBtn').onclick=menu;$('#homeBtn').onclick=()=>show('#home');$('#backBtn').onclick=menu;$('#mapBtn').onclick=()=>{$('#result').close();menu()};$('#nextBtn').onclick=()=>{$('#result').close();const i=stages.indexOf(current);i<5?start(stages[i+1]):menu()};document.querySelectorAll('.mission').forEach(b=>b.onclick=()=>start(b.dataset.stage));
function start(s){current=s;stageScore=0;$('#stageScore').textContent=0;const map={vocab:['Vocabulary Match','จับคู่ภาพกับคำศัพท์'],listen:['Listening Challenge','ฟังแล้วเลือกภาพ'],read:['Read & Choose','อ่านคำใบ้แล้วเลือกคำตอบ'],grammar:['This or That?','เลือก This is / That is'],speak:['Speak & Ask','ฝึกพูดถาม-ตอบ'],create:['Create & Draw','วาดของเล่นที่ชอบ']};$('#stageTitle').textContent=map[s][0];$('#stageSub').textContent=map[s][1];show('#game');({vocab,listen,read,grammar,speakStage,create})[s]()}
function vocab(){let selected=null,count=0;$('#stageArea').innerHTML='<div class="panel"><p class="instruction">Match each word with the correct picture.</p><div id="bank" class="word-bank"></div><div id="pics" class="grid"></div></div>';shuffle(toys).forEach(t=>{const b=document.createElement('button');b.textContent=t.w;b.onclick=()=>{selected=t.w;speak(t.w)};$('#bank').appendChild(b)});shuffle(toys).forEach(t=>{const c=document.createElement('button');c.className='toy';c.innerHTML=`<span class="emoji">${t.e}</span>`;c.onclick=()=>{if(!selected)return;if(selected===t.w){c.classList.add('correct');c.innerHTML+=`<span class="word">${t.w}</span>`;[...$('#bank').children].find(x=>x.textContent===t.w)?.remove();count++;add(10);beep();speak(`Great! ${t.w}.`);selected=null;if(count===8)setTimeout(()=>finish('You matched all 8 toy words!'),500)}else{c.classList.add('wrong');beep(false);setTimeout(()=>c.classList.remove('wrong'),400)}};$('#pics').appendChild(c)})}
function listen(){let q=0,score=0;$('#stageArea').innerHTML='<div class="panel listen"><p class="instruction">Listen and choose the correct picture.</p><button id="listenBtn">🔊</button><div id="q" class="question"></div><div id="opts" class="grid"></div></div>';function next(){if(q===8)return finish(`You got ${score} out of 8 correct!`);const target=toys[q],opts=shuffle([target,...shuffle(toys.filter(x=>x.w!==target.w)).slice(0,3)]);$('#q').textContent=`Question ${q+1} / 8`;$('#opts').innerHTML='';opts.forEach(t=>{const b=document.createElement('button');b.className='toy';b.innerHTML=`<span class="emoji">${t.e}</span>`;b.onclick=()=>{if(t.w===target.w){score++;add(10);beep();speak(`Correct! ${target.w}.`);q++;setTimeout(next,600)}else{b.classList.add('wrong');beep(false);setTimeout(()=>b.classList.remove('wrong'),400)}};$('#opts').appendChild(b)});setTimeout(()=>speak(`Pick ${target.w}.`),250)}$('#listenBtn').onclick=()=>speak(`Pick ${toys[q].w}.`);next()}
function read(){const clues=[['It is soft. I hug it.','teddy bear'],['It has wheels. I push it.','car'],['I can fly it in the sky.','kite'],['I can build with it.','puzzle'],['I play with it in the park.','ball']];let q=0;$('#stageArea').innerHTML='<div class="panel"><p class="instruction">Read the clue and choose the toy.</p><div id="readBox"></div></div>';function next(){if(q===clues.length)return finish('You solved all reading clues!');const [clue,ans]=clues[q],target=toys.find(t=>t.w===ans),opts=shuffle([target,...shuffle(toys.filter(t=>t.w!==ans)).slice(0,3)]);$('#readBox').innerHTML=`<div class="clue">${q+1}. ${clue}</div><div id="readGrid" class="grid"></div>`;opts.forEach(t=>{const b=document.createElement('button');b.className='toy';b.innerHTML=`<span class="emoji">${t.e}</span><span class="word">${t.w}</span>`;b.onclick=()=>{if(t.w===ans){add(15);beep();speak(`Correct! It is a ${ans}.`);q++;setTimeout(next,600)}else{b.classList.add('wrong');beep(false);setTimeout(()=>b.classList.remove('wrong'),400)}};$('#readGrid').appendChild(b)})}next()}
function grammar(){const qs=[['teddy bear','This is'],['robot','That is'],['ball','This is'],['train','That is']];let q=0;$('#stageArea').innerHTML='<div class="panel"><p class="instruction">Choose “This is ...” or “That is ...”</p><div id="gram"></div></div>';function next(){if(q===qs.length)return finish('Grammar mission complete!');const [w,ans]=qs[q],t=toys.find(x=>x.w===w);$('#gram').innerHTML=`<div class="question">${t.e}<br>_____ a ${w}.</div><div class="choices"><button>This is</button><button>That is</button></div>`;document.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>{if(b.textContent===ans){add(15);beep();speak(`${ans} a ${w}.`);q++;setTimeout(next,600)}else{beep(false)}})}next()}
function speakStage(){let q=0;$('#stageArea').innerHTML='<div class="panel speech"><p class="instruction">Listen, then speak.</p><div id="speakBox"></div></div>';function next(){if(q===4)return finish('You practised 4 speaking sentences!');const t=toys[q*2],line=q%2===0?`What is this? It is a ${t.w}.`:`What is that? It is a ${t.w}.`;$('#speakBox').innerHTML=`<div class="emoji">${t.e}</div><div class="model">${line}</div><div class="actions"><button id="modelBtn">🔊 Listen</button><button id="micBtn" class="mic">🎤</button><button id="saidBtn">✅ I said it!</button></div><div id="heard"></div>`;$('#modelBtn').onclick=()=>speak(line);$('#saidBtn').onclick=()=>{add(15);beep();q++;setTimeout(next,300)};$('#micBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#heard').textContent='Say the sentence, then tap “I said it!”';return}const r=new SR();r.lang='en-US';$('#heard').textContent='Listening...';r.onresult=e=>$('#heard').textContent=`You said: ${e.results[0][0].transcript}`;r.start()};setTimeout(()=>speak(line),300)}next()}
function create(){ $('#stageArea').innerHTML='<div class="panel"><p class="instruction">Draw your favorite toy and write 2 sentences.</p><div class="draw"><canvas id="canvas" width="900" height="600"></canvas><div class="tools"><input placeholder="My favorite toy is..."><textarea rows="3" placeholder="1. It is..."></textarea><textarea rows="3" placeholder="2. I can..."></textarea><div class="actions"><button id="black">✏️ Pencil</button><button id="pink">🖍️ Crayon</button><button id="clear">🧽 Clear</button></div><div class="stars"><p>I can say the toy words.</p><button>☆</button><button>☆</button><button>☆</button></div><button id="finishCreate" class="primary big">✅ Finish My Work</button></div></div></div>';const c=$('#canvas'),ctx=c.getContext('2d');let d=false;ctx.lineWidth=8;ctx.lineCap='round';ctx.strokeStyle='#222';const p=e=>{const r=c.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:(t.clientX-r.left)*c.width/r.width,y:(t.clientY-r.top)*c.height/r.height}};const st=e=>{d=true;const a=p(e);ctx.beginPath();ctx.moveTo(a.x,a.y);e.preventDefault()};const mv=e=>{if(!d)return;const a=p(e);ctx.lineTo(a.x,a.y);ctx.stroke();e.preventDefault()};c.addEventListener('mousedown',st);c.addEventListener('mousemove',mv);window.addEventListener('mouseup',()=>d=false);c.addEventListener('touchstart',st,{passive:false});c.addEventListener('touchmove',mv,{passive:false});c.addEventListener('touchend',()=>d=false);$('#black').onclick=()=>ctx.strokeStyle='#222';$('#pink').onclick=()=>ctx.strokeStyle='#ef4e8d';$('#clear').onclick=()=>ctx.clearRect(0,0,c.width,c.height);document.querySelectorAll('.stars button').forEach((b,i,a)=>b.onclick=()=>a.forEach((x,j)=>x.textContent=j<=i?'⭐':'☆'));$('#finishCreate').onclick=()=>{add(20);finish('Wonderful drawing and writing!')}}
